sudo: false

language: go

go:
  - 1.x
  - master

script:
  - env GO111MODULE=on make

deploy:
- provider: script
  skip_cleanup: true
  script: curl -sL https://git.io/goreleaser | bash
  on:
    tags: true
    condition: $TRAVIS_OS_NAME = linux
